### ISSUE TITLE
Skip DLC Download

### ISSUE THREAD

**Issue by Memeheader** [seuyh/stellaris-dlc-unlocker#1]
You need to add an option to skip the DLC download, I already have the DLC. I just need the unlocker. It takes hours to download DLC and it gets stuck everytime.

**Comment by seuyh** [comment]
I've been suggested something like this before, I think it's a good idea, but when using such a function, you need to check that all the dlc is really there. I have a cooler idea for this, I can check what dlc has a person, and download only those that are needed, but in this case manually skip the download will still not be possible, it will have to determine automatically whether it is needed. I also want to add the ability to directly download the archive with dlc with the ability to specify the path to it, for those people who have problems when downloading through the installer itself. Thanks for the suggestion, I will try to realize it in the near future!

**Comment by seuyh** [comment]
0.97 Added automatic skip download if dlc is already installed
