### ISSUE TITLE
Please support MacOS

### ISSUE THREAD

**Issue by ArtomYuan** [seuyh/stellaris-dlc-unlocker#12]
Please support MacOS

**Comment by wuyilingwei** [comment]
MacOS need other patch file, I only find this file, it still have some problem and it is very old patch way.
[StellarisMacDLCunlockerWithoutOnline.zip](https://github.com/user-attachments/files/15741169/StellarisMacDLCunlockerWithoutOnline.zip)

**Comment by ArtomYuan** [comment]
Okay, thank you very much. I'll give it a try
________________________________
发件人: Mr. Lei ***@***.***>
发送时间: 2024年6月7日 22:37
收件人: seuyh/stellaris-dlc-unlocker ***@***.***>
抄送: ArtomYuan ***@***.***>; Author ***@***.***>
主题: Re: [seuyh/stellaris-dlc-unlocker] Please support MacOS (Issue #12)


MacOS need other patch file, I only find this file, it still have some problem and it is very old patch way.
StellarisMacDLCunlockerWithoutOnline.zip<https://github.com/user-attachments/files/15741169/StellarisMacDLCunlockerWithoutOnline.zip>

―

**Comment by ArtomYuan** [comment]
> MacOS need other patch file, I only find this file, it still have some problem and it is very old patch way. [StellarisMacDLCunlockerWithoutOnline.zip](https://github.com/user-attachments/files/15741169/StellarisMacDLCunlockerWithoutOnline.zip)

Okay, thank you very much. I'll give it a try
