### ISSUE TITLE
Ошибка при установке модов после кряка dlc

### ISSUE THREAD

**Issue by DJTaDJuk** [seuyh/stellaris-dlc-unlocker#13]
![гитхаб](https://github.com/seuyh/stellaris-dlc-unlocker/assets/114240459/804c2fdf-7630-4434-9a0a-0c579698ffa9)
до кряка проблемы не было. Моды в игре не работают.
stellaris 3.12.4
dlc unlocker 1.12

**Comment by seuyh** [comment]
Не получилось воспроизвести, работает и установка и сами моды, проблема не в анлокере, могу посоветовать удалить файлы с названиями launcher-installer-windows*.msi (их 2 по идее) Затем проверить целостность файлов и еще раз воспользоваться анлокером

**Comment by DJTaDJuk** [comment]
а где эти файлы лежат?

**Comment by DJTaDJuk** [comment]
проблема решилась простой переустановкой лаунчера
