### ISSUE TITLE
Program wouldn't start after UAC auth

### ISSUE THREAD

**Issue by AuspiceGwan** [seuyh/stellaris-dlc-unlocker#14]
**Describe the bug**
Program wouldn't run after UAC auth, it is as if nothing was happening at all

**To Reproduce**
1. Run Program
2. Give Windows UAC auth
3. Nothing happens

**Desktop (please complete the following information):**
 - OS: Win10 Pro 22H2 19045.4651 with Ryzen 7900X

**Comment by seuyh** [comment]
it has a delay before starting just after UAC confirmation (5 seconds maximum) It is ok. If it doesn't start at all after that, then unfortunately I won't be able to reproduce such an error and understand why this happens

**Comment by wuyilingwei** [comment]
> **Describe the bug** Program wouldn't run after UAC auth, it is as if nothing was happening at all
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Run Program
> 2. Give Windows UAC auth
> 3. Nothing happens
> 
> **Desktop (please complete the following information):**
> 
> * OS: Win10 Pro 22H2 19045.4651 with Ryzen 7900X

Can I know your region?

**Comment by seuyh** [comment]
Try use VPN, in theory, this can help🧐

**Comment by wuyilingwei** [comment]
Dont forget check firewall, it may help.

**Comment by wuyilingwei** [comment]
However, we cannot solve problem without any detail, and just tell us "it not work".
