### ISSUE TITLE
启动程序后没有任何反应

### ISSUE THREAD

**Issue by BurningWater9** [seuyh/stellaris-dlc-unlocker#16]
**Describe the bug**
Stellaris-DLC-Unlocker.exe启动后选择是给与管理员身份运行后没有任何反应

**To Reproduce**
1. 启动程序
2. 选择是给与管理员身份运行
3. 没有任何反应

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
版本	Windows 10 教育版
版本号	22H2
操作系统内部版本	19045.4717
**Additional context**
我使用火绒杀毒软件 没有报毒或者隔离文件
我还需要提供什么信息?

**Comment by wuyilingwei** [comment]
开梯子了吗？可能是初始化的时候网络请求错误了

**Comment by NixonGreat** [comment]
一样的问题，开了梯子依然没有任何反应

**Comment by wuyilingwei** [comment]
呃，事件查看器windows日志中有应用程序错误记录吗？

**Comment by wuyilingwei** [comment]
怎么偏偏这个时候出问题（）
计划是用Java重构

**Comment by CrRinko** [comment]
一样的问题，不过梯子设置到全局就好了，估计还是网络的原因，建议启动时提供一个代理设置界面

**Comment by wuyilingwei** [comment]
This issue is related to the previous network problem that caused no response. I think it can be closed as resolved. @seuyh
