### ISSUE TITLE
DLC crash problem

### ISSUE THREAD

**Issue by IGROBRAT** [seuyh/stellaris-dlc-unlocker#19]
**Describe the bug**
So, the problem is - whenever you play with DLC "Cosmic Storms" enabled your game will crash at exactly 2210.01.01

**To Reproduce**
1. Download all DLC, and check if they are enabled
2. Start a game(Just choose a random race)
3. Set the game speed to max
4. Wait till 2210.01.01

**Expected behavior**
The game should crash giving you 2 options - to wait for it to load(it doesn't work) or to close the game.

**Screenshots**
Sadly, I can't really make a screenshot of it.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
The game works perfectly fine without the DLC "Cosmic Storms"

**Comment by wuyilingwei** [comment]
Re-run the dlc installer, turn off all mods and try again. In my test, I ran the original version to 2211+ without any crashes.
Avoid Intel 13/14 CPUs if possible

**Comment by seuyh** [comment]
just upload broken dlc, already fixed, delete DLC "Cosmic Storms" folder from game folder, and launch unlocker again

**Comment by Balphagorevr** [comment]
I noticed this too, the Cosmic storms DLC was downloaded and is missing the "dlc.033.zip" mentioned in the .dlc file. I just created an empty zip file and the game runs fine. The DLC does work but I am not sure if I am missing out on any music or sounds typically shipped in some other DLC's.

**Comment by GarryHuman** [comment]
I had reinstall game and launcher and game still crashes at 2210.01.01
Maybe stellaris has some configs, which i should reinstall?

**Comment by seuyh** [comment]
weird, maybe old dlc file was cached, try run on cmd this command -> "ipconfig /flushdns", also u can try to remove "Documents\Paradox Interactive\Stellaris" folder, but it delete ur saves and mods presets

**Comment by seuyh** [comment]
Ive found, most likely this  crash is a bug of the dlc, try to set the storms to 0 in the settings, I think the developers should fix it

**Comment by wuyilingwei** [comment]
I've seen reports that if all storms are set to 0, it will crash in 10 years. It may be that the forced judgment found that it cannot be generated.
Since I don't know your settings, please try turning on/off the storm (?)

**Comment by seuyh** [comment]
Worked
