### ISSUE TITLE
Defender false positive

### ISSUE THREAD

**Issue by Haeniken** [seuyh/stellaris-dlc-unlocker#2]
На последнюю сборку триггерит виндоус дефендер:

![image](https://github.com/seuyh/stellaris-dlc-unlocker/assets/56308597/bc1addc5-8880-4e54-82f8-8bbc2e22198d)
![image](https://github.com/seuyh/stellaris-dlc-unlocker/assets/56308597/e94142f6-460d-4d3d-b530-8d12292fae78)

**Comment by seuyh** [comment]
Это случается из-за механизма обновления, так уж он устроен, это проблема не только последней версии, этого можно было не замечать, так-как жалуется он совершенно рандомно, у кого то жалуется, у кого-то нет, от чего это зависит я так до конца и не понял
![image](https://github.com/seuyh/stellaris-dlc-unlocker/assets/71027218/1bcd54a5-5f22-42ea-b1b8-8e6b62d6a4d1)
