### ISSUE TITLE
3.13.1 Crash at Re-Download of Launcher

### ISSUE THREAD

**Issue by leitzta007** [seuyh/stellaris-dlc-unlocker#20]
**Describe the bug**
The Download crashes with an "unexpected Error" and closes

**To Reproduce**
1. Go to your stellaris
2. Click on the dlc unlocker
3. let him run and update to his latest version
4. See error after seeing him doing his stuff until described point

**Expected behavior**
It should have worked normally like last time i would think

**Screenshots**
Instead of a screenshot, i have an error log

**Desktop (please complete the following information):**
 - OS: Win10 Pro

**Additional context**
I already used the programm on 3.12, but it doesn't work for 3.13, so chose to re-use it
[unlocker_crashlog.txt](https://github.com/user-attachments/files/17118329/unlocker_crashlog.txt)

**Comment by seuyh** [comment]
Its new paradox launcher update, they just broke it. Please, click on "help" button on start page, and choose second option, then just continue installation, that's should be work

**Comment by valzargaming** [comment]
I can confirm that the "help" button to reinstall the launcher does not resolve the issue. Furthermore, something seems to be blatantly broken in the launcher when attempting to reinstall it from steam redistributable files or directly from the official website as the installers are either completely broken or reference a missing installer file from an older version.
[unlocker_crashlog.txt](https://github.com/user-attachments/files/17120926/unlocker_crashlog.txt)

The good news is this is almost a completely non-issue and Stellaris can still be launched directly from the .exe. I would recommend using a 3rd party mod manager if you absolutely must have a launcher.

**Comment by seuyh** [comment]
> I can confirm that the "help" button to reinstall the launcher does not resolve the issue. Furthermore, something seems to be blatantly broken in the launcher when attempting to reinstall it from steam redistributable files or directly from the official website as the installers are either completely broken or reference a missing installer file from an older version. [unlocker_crashlog.txt](https://github.com/user-attachments/files/17120926/unlocker_crashlog.txt)
> 
> The good news is this is almost a completely non-issue and Stellaris can still be launched directly from the .exe. I would recommend using a 3rd party mod manager if you absolutely must have a launcher.

I suppose your problem is related to something else, since solution I described has already helped several people

**Comment by tomb2000** [comment]
I'm getting the exact same issue. Its when it is on the last bit of the install when trying to uninstall the launcher then reinstall it always come up with an error. Any help? I have tried multiple times to restart the whole process but nothing works so far

**Comment by tomb2000** [comment]
I load up the game after this but it says the DLC can not be verified so I can't use it as well

**Comment by valzargaming** [comment]
Download [RegScanner](https://www.nirsoft.net/utils/regscanner.html)
Find String: "paradox launcher"
Check all "Scan the following base keys" options
Click "Scan"
Delete all found results that can be deleted
Reinstall the Paradox Launcher

I had originally tried finding the registry keys manually myself but searching from regedit takes so damn long I gave up.

**Comment by seuyh** [comment]
Fixed
