### ISSUE TITLE
游戏内无法正常使用dlc

### ISSUE THREAD

**Issue by ctrlkk** [seuyh/stellaris-dlc-unlocker#21]
**Describe the bug**
启动器显示有dlc但是未知所有者，游戏内无dlc

**Desktop (please complete the following information):**
 - OS: win10 22H2

**Error Logs**
Exception Type: FileNotFoundError
Exception Value: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\admin\\AppData\\Local\\Programs\\Paradox Interactive\\launcher\\launcher-v2.2024.14/resources/app.asar.unpacked/dist/main/steam_api64.dll' -> 'C:\\Users\\admin\\AppData\\Local\\Programs\\Paradox Interactive\\launcher\\launcher-v2.2024.14/resources/app.asar.unpacked/dist/main/steam_api64_o.dll'
Traceback:
  File "gui\main_window.py", line 495, in reinstall_2
    raise e
  File "gui\main_window.py", line 493, in reinstall_2
    self.replace_files(os.path.join(os.path.join(paradox_folder1, launcher_folders[0])))
  File "gui\main_window.py", line 516, in replace_files
    os.rename(f'{launcher_folder}/resources/{old_path}/dist/main/steam_api64.dll',

Exception Type: FileNotFoundError
Exception Value: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\admin\\AppData\\Local\\Programs\\Paradox Interactive\\launcher\\launcher-v2.2024.14/resources/app.asar.unpacked/dist/main/steam_api64.dll' -> 'C:\\Users\\admin\\AppData\\Local\\Programs\\Paradox Interactive\\launcher\\launcher-v2.2024.14/resources/app.asar.unpacked/dist/main/steam_api64_o.dll'
Traceback:
  File "gui\main_window.py", line 495, in reinstall_2
    raise e
  File "gui\main_window.py", line 493, in reinstall_2
    self.replace_files(os.path.join(os.path.join(paradox_folder1, launcher_folders[0])))
  File "gui\main_window.py", line 516, in replace_files
    os.rename(f'{launcher_folder}/resources/{old_path}/dist/main/steam_api64.dll',

Exception Type: FileNotFoundError
Exception Value: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\admin\\Documents\\Paradox Interactive\\Stellaris'
Traceback:
  File "gui\main_window.py", line 125, in in_game_fix
    rmtree(os.path.join(user_home, "Documents", "Paradox Interactive", "Stellaris"))
  File "shutil.py", line 758, in rmtree
  File "shutil.py", line 602, in _rmtree_unsafe
  File "shutil.py", line 599, in _rmtree_unsafe

Exception Type: FileNotFoundError
Exception Value: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\admin\\AppData\\Local\\Programs\\Paradox Interactive\\launcher\\launcher-v2.2024.14/resources/app.asar.unpacked/dist/main/steam_api64.dll' -> 'C:\\Users\\admin\\AppData\\Local\\Programs\\Paradox Interactive\\launcher\\launcher-v2.2024.14/resources/app.asar.unpacked/dist/main/steam_api64_o.dll'
Traceback:
  File "gui\main_window.py", line 495, in reinstall_2
    raise e
  File "gui\main_window.py", line 493, in reinstall_2
    self.replace_files(os.path.join(os.path.join(paradox_folder1, launcher_folders[0])))
  File "gui\main_window.py", line 516, in replace_files
    os.rename(f'{launcher_folder}/resources/{old_path}/dist/main/steam_api64.dll',

Exception Type: FileNotFoundError
Exception Value: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\admin\\Documents\\Paradox Interactive\\Stellaris'
Traceback:
  File "gui\main_window.py", line 125, in in_game_fix
    rmtree(os.path.join(user_home, "Documents", "Paradox Interactive", "Stellaris"))
  File "shutil.py", line 758, in rmtree
  File "shutil.py", line 602, in _rmtree_unsafe
  File "shutil.py", line 599, in _rmtree_unsafe

Exception Type: FileNotFoundError
Exception Value: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\admin\\AppData\\Local\\Programs\\Paradox Interactive\\launcher\\launcher-v2.2024.14/resources/app.asar.unpacked/dist/main/steam_api64.dll' -> 'C:\\Users\\admin\\AppData\\Local\\Programs\\Paradox Interactive\\launcher\\launcher-v2.2024.14/resources/app.asar.unpacked/dist/main/steam_api64_o.dll'
Traceback:
  File "gui\main_window.py", line 495, in reinstall_2
    raise e
  File "gui\main_window.py", line 493, in reinstall_2
    self.replace_files(os.path.join(os.path.join(paradox_folder1, launcher_folders[0])))
  File "gui\main_window.py", line 516, in replace_files
    os.rename(f'{launcher_folder}/resources/{old_path}/dist/main/steam_api64.dll',

**Comment by wuyilingwei** [comment]
I am not responsible for most of the code logic of this project, so I can only translate it for that author (打咩).
Report:
Describe the bug
The launcher shows that there is a dlc but the owner is unknown, and there is no dlc in the game
