### ISSUE TITLE
incorrect version tag for 1.14 version

### ISSUE THREAD

**Issue by nekokiwa** [seuyh/stellaris-dlc-unlocker#23]
The 1.14 version thinks it is still 1.13 and gets stuck trying to download a new update.

Run the exe and select a language. The auto updater will start.

After the update it should not try to update again or think it is 1.13.

Windows 10

**Comment by Daritergha** [comment]
Same problem.
1.14 shows update window, as it identifies as 1.13, and all attempts to update it (manually or automatically) lead to cycle.

**Comment by seuyh** [comment]
My fault, i already fixed this
