### ISSUE TITLE
You don't have this DLC

### ISSUE THREAD

**Issue by yin2hao** [seuyh/stellaris-dlc-unlocker#24]
First of all, some DLC won't download
Besides，an error is reported when the launcher is finally uninstalled and reinstalled
Occasionally, i can't enter the game, and when i enter the game, it will report an error and quit
Others，when i re-enter the Launcher and the game, i find that the existing DLC in the Launcher does not show that it is owned in the game
Finally，when i quit the game, it sometimes becomes unresponsive

<img width="408" alt="屏幕截图 2024-09-29 225011" src="https://github.com/user-attachments/assets/0b6d1d78-4825-4d62-8494-d5744c114cc3">
<img width="290" alt="屏幕截图 2024-09-29 225029" src="https://github.com/user-attachments/assets/278a2ece-06e8-4b15-abb1-52424509ec43">
<img width="1280" alt="屏幕截图 2024-09-29 225139" src="https://github.com/user-attachments/assets/21cdb64b-3118-46f9-8ca6-baf99c6bd1da">
<img width="1269" alt="屏幕截图 2024-09-29 225200" src="https://github.com/user-attachments/assets/9a4d6640-9ec0-4181-9a05-e4ab4228a329">

**Comment by szmit1** [comment]
O u have this same problem like me , tho the problem fr me is that the game dont see i ` have dlc verified`

**Comment by seuyh** [comment]
Press the "Help" button on unlocker start page and then choose second option

**Comment by yin2hao** [comment]
> Press the "Help" button on unlocker start page and then choose second option

i had tried it but it didn't work as usuall

**Comment by seuyh** [comment]
fixed
