### ISSUE TITLE
So i use the program to unlock last 3 dlc i didint have , and after instaling  the paradox launcher i got x error , and then in launcehr it say they cant verify ownershp of dlc 

### ISSUE THREAD

**Issue by szmit1** [seuyh/stellaris-dlc-unlocker#25]
So i use the program to unlock last 3 dlc i didint have , and after instaling  the paradox launcher i got x error , and then in launcher it say they cant verify ownershp of dlc

**Comment by PidorPereodetii** [comment]
Press the "Help, nothing doesn't works" and then choose "Launcher cannot verify dlc". Worked for me

**Comment by szmit1** [comment]
That help, thx
