### ISSUE TITLE
v1.14 release crashes without error

### ISSUE THREAD

**Issue by valzargaming** [seuyh/stellaris-dlc-unlocker#26]
**Describe the bug**
The installer crashes with an empty error window after reinstalling the launcher.

**To Reproduce**
Run the installer.

**Expected behavior**
The installer shouldn't crash without even generating an error log.

**Screenshots**
![image](https://github.com/user-attachments/assets/d4a91230-8d5c-4b88-9bfd-19635fd72a43)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by valzargaming** [comment]
Using the option to reinstall the launcher at the beginning of the prompts resolved the issue.

**Comment by valzargaming** [comment]
Quick update on this because it did not, in fact, fix the issue. The system's registry at HKCU\Software\Microsoft\Installer\Products\ADFC9978C49C2A74E90F71B08CF4887C\SourceList was linking a bad installer version, and deleting the registry entry allowed the installer to work properly again. It was referencing a bad name (older version) for the official installer.

**Comment by seuyh** [comment]
these are garbage paths in the registry, they should not affect the unlocker in any way, I take information for the launcher by path HCU\Software\Paradox Interactive\Paradox Launcher v2 in "LauncherInstallation" value.
Weird

**Comment by valzargaming** [comment]
The issue seems to be related to how the Paradox installer itself works. In this case, it had some junk data indicating the expected name for the installer and its filepath, neither of which were correct, so when the Paradox installer ran it would run into an error stating that the expected .msi file wasn't found. Because the official Paradox installer couldn't run or install properly neither could the unlocker find or reinstall it. I still have no idea what actually caused this issue to happen in the first place as this was the only thing I ever used other than the base game. 🤷
