### ISSUE TITLE
Creamapi not Generating

### ISSUE THREAD

**Issue by orcadude** [seuyh/stellaris-dlc-unlocker#27]
"Generating creamapi" is not increasing from 0%

![image](https://github.com/user-attachments/assets/5844e943-4fe1-46df-b708-cbb0a6fcefb0)

**Comment by XumetaXD** [comment]
Having the same Issue

**Comment by seuyh** [comment]
Steamcmd site is down right now, don't work right now, just wait

**Comment by alucard87pl** [comment]
If I leave the unlocker running, will it complete when the site is back online, or should I just try after some time?
https://status.steamcmd.net/ shows it operational, but that's just the API, I guess, not the site itself?

**Comment by seuyh** [comment]
Fixed
