### ISSUE TITLE
Stellaris is deleted when reinstalling the launcher

### ISSUE THREAD

**Issue by EvilLaplase** [seuyh/stellaris-dlc-unlocker#29]
I gave Stellaris to my friend. He installed the game from Steam, launched the unlocker, manually selected the game folder, after the DLC installation stage, the launcher began to reinstall, and then everything crashed with an error, and the game files were deleted.
[unlocker (1).log](https://github.com/user-attachments/files/17428206/unlocker.1.log)

**Comment by EvilLaplase** [comment]
The problem was solved, after a few days of reinstalling it turned out that launcher-v2-bootstrapper was installed in the game folder, which led to the deletion of the entire folder with its contents.
I will leave the question open so that the author reads this.

**Comment by seuyh** [comment]
I know about this problem thx, but i dont know how this happen, why sometimes launcher installs into game folder
