### ISSUE TITLE
EXE dont starts

### ISSUE THREAD

**Issue by AVir3307** [seuyh/stellaris-dlc-unlocker#3]
**Describe the bug**
EN: I have a problem with running the exe installer. I downloaded the latest version from the website, but it wouldn't start (at least, it wouldn't show a window or start loading). After a few more attempts, I got into the code, which resulted in a window that would launch. Without fixes it only offered to download a new version (even though I already had the latest version of the code). Having cut file checking out of the code, I managed to enter the installer. Despite the enabled VPN (I am from Ukraine) the program crashed with a request to enable it. At the next restart let me go on, but at the moment of reinstalling the launcher threw an error (screenshot below). Following the instructions did not change anything and I have no idea how to fix it. I hope for your help.

RU: У меня есть проблема с запуском exe установщика. Я скачал последнюю версию с сайта, но она не запускалась (по крайней мере не появлялось окно, не начиналась загрузка). После еще нескольких попыток залез в код, в результате чего получилось запустить окно. Без исправлений оно только предлагало скачать новую версию (даже не смотря на то, что у меня и так стояла последняя версия кода). Вырезав из кода проверку файлов получилось зайти в установщик. Несмотря на включенный ВПН (я из Украины) программа упала с просьбой его включить. При очередном перезапуске пустило дальше, но на моменте переустановки лаунчера выбила ошибку (скрин ниже). Следование инструкциям ничего не изменило и я без понятия как это исправить. Надеюсь на вашу помощь.

**To Reproduce**
1. Go to programm code
2. Remove version check (change if condition to False)
3. Start programm 
4. Try to install normally
5. Face error on reinstall launcher

**Screenshots**
![image](https://github.com/seuyh/stellaris-dlc-unlocker/assets/78906592/6f77d91f-f549-4b20-837a-6df2c6b269e1)
![image](https://github.com/seuyh/stellaris-dlc-unlocker/assets/78906592/a7f3f0d7-0a9d-46a0-9039-b2fa739d10a8)

**Desktop (please complete the following information):**
 - OS: Windows 11
 
**Additional context**
I'm from Ukrain so that can influense (downloading domain is .ru so I can't open it without VPN)
Я из Украины так что это могло повлиять (загрузка идет с .ru домена который я не могу открыть без VPN)

**Comment by seuyh** [comment]
Привет! Что насчет ошибки со скриншотов, то это скорее всего следствие нестабильного VPN из-за чего некоторые архивы скачиваются поврежденными, решение могу пока предложить такое: скачать целиком dlc отдельно, например [отсюда](https://mega.nz/file/Qv1HibzS#bJyIaLAgqRD3SHf7qhPin300-CaGdMlJKHHGBtYQvzo) и распаковать содержимое архива в папку "dlc" в папке с игрой. В будущем я думаю добавлю еще 1 сервер, чтобы был без региональных ограничений.

>  только предлагало скачать новую версию (даже не смотря на то, что у меня и так стояла последняя версия кода)

Насчет этого, это странно если честно, потому, что тут уже все качается напрямую с гитхаба, да и если стоит последняя версия, такого происходить не должно, попробуй скачать последнюю версию напрямую [отсюда](https://github.com/seuyh/stellaris-dlc-unlocker/releases/tag/1.1)

**Comment by AVir3307** [comment]
Привет

> Насчет этого, это странно если честно, потому, что тут уже все качается напрямую с гитхаба, да и если стоит последняя версия, такого происходить не должно, попробуй скачать последнюю версию напрямую [отсюда](https://github.com/seuyh/stellaris-dlc-unlocker/releases/tag/1.1)

Это не помогло, но когда скачал dlc все заработало. Спасибо за помощь и за анлокер.
