### ISSUE TITLE
The dlc's aren't passing the games verification.

### ISSUE THREAD

**Issue by Devspace007** [seuyh/stellaris-dlc-unlocker#34]
so the game sees the files but will not verify, know a way to get around this? 

![Screenshot 2024-11-12 003751](https://github.com/user-attachments/assets/01172ec9-cbbd-4639-a69a-9f132e27c8d4)

**Comment by seuyh** [comment]
Launcher version?

**Comment by Devspace007** [comment]
2024.16-rc3?

**Comment by Devspace007** [comment]
> Launcher version?

2024.16-rc3?

**Comment by seuyh** [comment]
I don't know this version mb they changing something else again, ill check it

**Comment by seuyh** [comment]
![image](https://github.com/user-attachments/assets/35c08c39-6a63-49fa-895d-612134121c8b)
but it latest
![image](https://github.com/user-attachments/assets/53cba91d-dfea-401f-beed-9d375008acd1)
please turn off beta versions

**Comment by seuyh** [comment]
![image](https://github.com/user-attachments/assets/4875d74f-e2d0-4e4f-a70c-a6b9bc1edd26)
and check what installer version in main game directory if it not 2024.14 or 2024.15 delete this.msi file then verify files via steam

**Comment by Devspace007** [comment]
> > ![image](https://private-user-images.githubusercontent.com/71027218/385164446-4875d74f-e2d0-4e4f-a70c-a6b9bc1edd26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MzY3MDksIm5iZiI6MTczMTQzNjQwOSwicGF0aCI6Ii83MTAyNzIxOC8zODUxNjQ0NDYtNDg3NWQ3NGYtZTJkMC00ZTRmLWE3MGMtYTZiOWJjMWVkZDI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE4MzMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZjY4NmNlZTY5ZmI2YTM2MGFmMjdkOGNkZDk4MTRkZjQxMTU2N2QzNThkZTcwNzYxMzcyMWUwNDhjYTA2NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EbgeaVC1BjLqIUOU9IwQaR6gNr1GkKsLG3IYhJcn8Uk) and check what installer version in main game directory if it not 2024.14 or 2024.15 delete this.msi file then verify files via steam
> 
> never mind, i removed the launcher for real, my bad
> 
> and after testing it, they are still unverified, i'm going to redo they way i put in the dlcs, maybe its not the launcher.
> 
> ok, that dint work either... since i did the manual way, let me use your installer and ill see if that fixes it.

well until i can get a server connection the installer wont work.

**Comment by seuyh** [comment]
It may not be available in some regions, you can simply agree to open it and after completing what is written on the screen, continue using it without connecting

**Comment by Devspace007** [comment]
![Screenshot 2024-11-13 180614](https://github.com/user-attachments/assets/077e9bb0-be47-432c-9e4c-6925ab916faa)

it does give this however i got around it (it was another tab) and did launch game through the installer and it works! didn't crash and still works with clicking the one on desktop if i get out, so yea thanks alot!

**Comment by ThatDudeLolMan** [comment]
> ![image](https://github.com/user-attachments/assets/4875d74f-e2d0-4e4f-a70c-a6b9bc1edd26) and check what installer version in main game directory if it not 2024.14 or 2024.15 delete this.msi file then verify files via steam

How do i verify via steam?
