### ISSUE TITLE
Error with connection to server

### ISSUE THREAD

**Issue by DJTaDJuk** [seuyh/stellaris-dlc-unlocker#35]
Error appear when i start unlocker. Tried VPN(USA, Poland, Romania).

here's the screenshot:
![image](https://github.com/user-attachments/assets/f3e08b07-43ce-4d27-b1b8-3e9de482f8e2)

**Comment by seuyh** [comment]
yes, I know, the provider has changed the ip addresses, it takes a little time for the dns to be updated

**Comment by DJTaDJuk** [comment]
okay, thank you
