### ISSUE TITLE
Failed to decompress

### ISSUE THREAD

**Issue by wuyilingwei** [seuyh/stellaris-dlc-unlocker#40]
After the download is complete, an extraction error is displayed
![image](https://github.com/user-attachments/assets/740a32a8-5a96-4e29-95f4-5df00f84a61a)

_Originally posted by @yao1576 in https://github.com/seuyh/stellaris-dlc-unlocker/discussions/39_

**Comment by wuyilingwei** [comment]
Is there a log? @yao1576

**Comment by yao1576** [comment]
But there are still 3 shows that are not unlocked
![屏幕截图 2024-12-21 005256](https://github.com/user-attachments/assets/ac52b1c4-4ad0-44e0-a99f-9b880ba4adc5)

**Comment by wuyilingwei** [comment]
应该是下载出了一点问题，有重试吗？
刚好日志也是表明有三个压缩包解压错误

**Comment by yao1576** [comment]
我应该如何重试？我已经重启应用程序很多次，也换过我的网络，也将程序重新安装过

**Comment by wuyilingwei** [comment]
从这里下载dlc文件 https://mega.nz/folder/4zFRnD6a#aVGAK32ZHPxCp7bMtG87BA 并且在游戏目录的dlc文件中覆盖解压错误的那三个dlc

**Comment by wuyilingwei** [comment]
@seuyh Could you check that 3 dlcs file in your server is working? Or are these 3 DLCs different from the others in some way (like being bigger?)

**Comment by yao1576** [comment]
已经可以了谢谢你

**Comment by yao1576** [comment]
已经可以了谢谢你

**Comment by wuyilingwei** [comment]
那我关issue了
