### ISSUE TITLE
При переустановке лаунчера крашится

### ISSUE THREAD

**Issue by PerceptControl** [seuyh/stellaris-dlc-unlocker#5]
[unlocker_crashlog.txt](https://github.com/seuyh/stellaris-dlc-unlocker/files/15328114/unlocker_crashlog.txt)

**Comment by seuyh** [comment]
Какие то траблы при переустановке лаунчера, проверьте есть ли файл launcher-installer{приписка версии}.msi а так же возможность открыть этот файл, после можно проверить возможность выполнения команд в командной строке, а именно "cmd" и "msiexec", но самым верочным вариантом решения этой проблемы будет полное удаления лаунчера и игры и последующая их установка, это в 90% случаев решит проблему
