### ISSUE TITLE
Опечатка в установщике

### ISSUE THREAD

**Issue by Ololopony** [seuyh/stellaris-dlc-unlocker#8]
Добрый день, заметил вот такую опечатку в слове текущего. Ниже прилагаю скриншот.

![Снимок экрана 2024-05-26 192925](https://github.com/seuyh/stellaris-dlc-unlocker/assets/87032414/985ed20f-d6b7-44b7-91d5-2a500341b5ea)

**Comment by seuyh** [comment]
а ой, спасибо, исправлю
